# Generated by Django 4.2.7 on 2023-11-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Cargo')),
                ('carga_horaria', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Carga horária')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('email', models.CharField(max_length=11, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Salario')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Manutenção',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(verbose_name='Data pedido')),
                ('data_entrega', models.DateTimeField(verbose_name='Data entrega')),
                ('descricao', models.CharField(max_length=300, verbose_name='Decrição do erro')),
                ('funcionarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Loja_Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=50, verbose_name='CPNJ')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('funcionarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('email', models.CharField(max_length=11, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(max_length=11, unique=True, verbose_name='Telefone')),
                ('entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
