# Generated by Django 4.2.7 on 2023-11-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='loja_celular',
            options={'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AlterModelOptions(
            name='manutenção',
            options={'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.RemoveField(
            model_name='manutenção',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='manutenção',
            name='data_pedido',
        ),
        migrations.AddField(
            model_name='manutenção',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Custo da Manutenção'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='entrega',
            field=models.CharField(default=1, max_length=50, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(verbose_name='Data pedido')),
                ('data_entrega', models.DateTimeField(verbose_name='Data entrega')),
                ('status_pedido', models.BooleanField(verbose_name='Finalizado')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.cliente')),
            ],
        ),
    ]
