# Generated by Django 4.2.7 on 2023-11-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_pedido_manuntecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalhesCelular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=300, verbose_name='Fabricante')),
                ('sistema_operacionasl', models.IntegerField(choices=[(1, 'Android'), (2, 'iOS'), (3, 'Outros')], default=3)),
                ('ram', models.IntegerField(verbose_name='Memória Ram')),
                ('armazenamento', models.IntegerField(verbose_name='Armazenamento')),
            ],
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Celular')),
                ('celular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.detalhescelular')),
            ],
        ),
    ]
