# Generated by Django 4.2.7 on 2023-11-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_detalhescelular_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome do celular')),
                ('fabricante', models.CharField(max_length=300, verbose_name='Fabricante')),
                ('sistema_operacionasl', models.IntegerField(choices=[(1, 'Android'), (2, 'iOS'), (3, 'Outros')], default=3)),
                ('ram', models.IntegerField(verbose_name='Memória Ram')),
                ('armazenamento', models.IntegerField(verbose_name='Armazenamento')),
            ],
        ),
        migrations.AlterModelOptions(
            name='celular',
            options={'verbose_name': 'Celular', 'verbose_name_plural': 'Celulares'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='celular',
            name='celular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.modelo'),
        ),
        migrations.DeleteModel(
            name='DetalhesCelular',
        ),
    ]
