# Generated by Django 4.2.7 on 2023-11-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_alter_celular_celular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
        migrations.AddField(
            model_name='loja_celular',
            name='celulares',
            field=models.ManyToManyField(to='aplic.celular'),
        ),
    ]
