# Generated by Django 4.2.7 on 2023-11-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_alter_modelo_options_loja_celular_celulares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome do celular')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.RemoveField(
            model_name='celular',
            name='celular',
        ),
        migrations.AddField(
            model_name='celular',
            name='armazenamento',
            field=models.IntegerField(default=1, verbose_name='Armazenamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='fabricante',
            field=models.CharField(default=1, max_length=300, verbose_name='Fabricante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='nome',
            field=models.CharField(default=1, max_length=300, verbose_name='Nome do celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='ram',
            field=models.IntegerField(default=1, verbose_name='Memória Ram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='celular',
            name='sistema_operacionasl',
            field=models.IntegerField(choices=[(1, 'Android'), (2, 'iOS'), (3, 'Outros')], default=3),
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
        migrations.AddField(
            model_name='celular',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.fornecedor'),
        ),
    ]
