# Generated by Django 4.2.7 on 2023-11-24 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0008_fornecedor_remove_celular_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('numero', models.CharField(max_length=50, verbose_name='Numero')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AlterField(
            model_name='cargo',
            name='carga_horaria',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Carga horária'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.endereco'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.endereco'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.endereco'),
        ),
        migrations.AlterField(
            model_name='loja_celular',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.endereco'),
        ),
    ]
