# Generated by Django 4.2.7 on 2023-11-24 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0009_endereco_alter_cargo_carga_horaria_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd', models.CharField(max_length=5, verbose_name='Código de Área')),
                ('numero', models.CharField(max_length=15, verbose_name='Número de Telefone')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='loja_celular',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cliente', to='aplic.cliente'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='fornedor_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Fornecedot', to='aplic.fornecedor'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='loja_end',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Loja', to='aplic.loja_celular'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=300, verbose_name='Nome do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.telefone'),
        ),
    ]
